### ISSUE TITLE
Android13打开App的崩溃日志

### ISSUE THREAD

**Issue by MEi521010** [MaYiFei1995/HEGUIDemo#1]
红米K40机型 Android13

java.lang.IllegalArgumentException: com.mai.hegui.demo: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
 at android.app.PendingIntent.checkFlags(PendingIntent.java:404)
 at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:674)
 at android.app.PendingIntent.getBroadcast(PendingIntent.java:661)
 at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
 at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
 at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
 at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)

**Comment by MaYiFei1995** [comment]
参照[[How to resolve "Missing PendingIntent mutability flag" lint warning in android api 30+?](https://stackoverflow.com/questions/67045607/how-to-resolve-missing-pendingintent-mutability-flag-lint-warning-in-android-a)](https://stackoverflow.com/questions/67045607/how-to-resolve-missing-pendingintent-mutability-flag-lint-warning-in-android-a)升级AdMob版本修复

a6eadd2b564baf472ae66f8bec98bca8f2d179be
